CREATE TABLE IF NOT EXISTS `forecasting-mentions-project.forecasting_mentions.web_mentions_candidates`
CLUSTER BY domain,person
OPTIONS(description='GDELT Russian-language surname candidate tokens. Raw repeated occurrences retained. Requires source/person and duplicate audit. Common leading punctuation ranges only.') AS
SELECT date AS seen_at,DATE(date,'Europe/Moscow') AS day,NET.HOST(url) AS domain,url,ngram,pos,pre,post,
CASE WHEN REGEXP_CONTAINS(LOWER(ngram),'сталин') THEN 'stalin' WHEN REGEXP_CONTAINS(LOWER(ngram),'ленин') THEN 'lenin' ELSE 'trump' END AS person
FROM `gdelt-bq.gdeltv2.webngrams`
WHERE date >= TIMESTAMP('2023-01-01') AND date < TIMESTAMP('2026-10-03') AND lang='ru'
AND ((ngram >= 'Сталин' AND ngram < 'Сталиня') OR (ngram >= 'сталин' AND ngram < 'сталиня') OR (ngram >= 'Ленин' AND ngram < 'Лениня') OR (ngram >= 'ленин' AND ngram < 'лениня') OR (ngram >= 'Трамп' AND ngram < 'Трампя') OR (ngram >= 'трамп' AND ngram < 'трампя') OR (ngram >= '«Сталин' AND ngram < '«Сталиня') OR (ngram >= '«сталин' AND ngram < '«сталиня') OR (ngram >= '«Ленин' AND ngram < '«Лениня') OR (ngram >= '«ленин' AND ngram < '«лениня') OR (ngram >= '«Трамп' AND ngram < '«Трампя') OR (ngram >= '«трамп' AND ngram < '«трампя') OR (ngram >= '"Сталин' AND ngram < '"Сталиня') OR (ngram >= '"сталин' AND ngram < '"сталиня') OR (ngram >= '"Ленин' AND ngram < '"Лениня') OR (ngram >= '"ленин' AND ngram < '"лениня') OR (ngram >= '"Трамп' AND ngram < '"Трампя') OR (ngram >= '"трамп' AND ngram < '"трампя') OR (ngram >= '(Сталин' AND ngram < '(Сталиня') OR (ngram >= '(сталин' AND ngram < '(сталиня') OR (ngram >= '(Ленин' AND ngram < '(Лениня') OR (ngram >= '(ленин' AND ngram < '(лениня') OR (ngram >= '(Трамп' AND ngram < '(Трампя') OR (ngram >= '(трамп' AND ngram < '(трампя') OR (ngram >= '[Сталин' AND ngram < '[Сталиня') OR (ngram >= '[сталин' AND ngram < '[сталиня') OR (ngram >= '[Ленин' AND ngram < '[Лениня') OR (ngram >= '[ленин' AND ngram < '[лениня') OR (ngram >= '[Трамп' AND ngram < '[Трампя') OR (ngram >= '[трамп' AND ngram < '[трампя') OR (ngram >= '“Сталин' AND ngram < '“Сталиня') OR (ngram >= '“сталин' AND ngram < '“сталиня') OR (ngram >= '“Ленин' AND ngram < '“Лениня') OR (ngram >= '“ленин' AND ngram < '“лениня') OR (ngram >= '“Трамп' AND ngram < '“Трампя') OR (ngram >= '“трамп' AND ngram < '“трампя'))
AND REGEXP_CONTAINS(LOWER(ngram),r'^[^а-яё]*(сталин(а|у|ым|е)?|ленин(а|у|ым|е)?|трамп(а|у|ом|е)?)[^а-яё]*$');
